training:
  device: auto            # auto|cpu|cuda
  mixed_precision: true
  random_seed: 42
  early_stopping_patience: 5

logging:
  checkpoint_dir: checkpoints/professional
  log_dir: logs/professional
  use_tensorboard: true
  use_wandb: false
  wandb_project: abr-diffusion
  log_interval: 50
  val_preview_samples: 8

data:
  path: data/processed/ultimate_dataset_with_clinical_thresholds.pkl
  batch_size: 64
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 0           # safer on macOS; set 4+ on Linux/GPU
  pin_memory: false        # set true if using CUDA

model:
  signal_length: 200
  static_dim: 4
  base_channels: 64
  n_levels: 4
  dropout: 0.1
  s4_state_size: 64
  num_s4_layers: 2
  num_transformer_layers: 2
  num_heads: 8
  # num_classes: 5         # optional; auto-detected if omitted

diffusion:
  schedule_type: cosine
  num_timesteps: 1000

optimization:
  epochs: 1               # smoketest; increase for real training
  learning_rate: 0.0002
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  accumulation_steps: 1
  warmup_epochs: 1
  ema_decay: 0.999
  classification_weight: 0.0

